export type BrochureSectionId =
  | 'intro'
  | 'fertility'
  | 'fibromyalgia'
  | 'lower-back-pain'
  | 'sciatica'
  | 'stop-smoking'
  | 'weight-loss'
  | 'migraine'
  | 'joint-pain'
  | 'sports-injuries'
  | 'insomnia'
  | 'anxiety'
  | 'menopause'
  | 'dry-eye';
